name: 'ispw-sync-local'
description: 'Sync a changeset to the mainframe using ISPW local CLI'
branding:
  icon: upload-cloud
  color: orange
author: 'BMC'
inputs:
  host:
    description: 'The host name or IP to be connected'
    required: true
  port: 
    description: 'The port to be connected'
    required: true
  encryptionProtocol:
    description: 'The encryption protocol for the connection (None, Auto, SSLv3, TLS, TLSv1, TLSv1.1, TLSv1.2)'
    required: false
    default: 'None'
  codePage:
    description: 'The code page for the connection'
    required: false
    default: '1047'
  timeout:
    description: 'The timeout (in minutes) for the connection'
    required: false
    default: '0'
  uid: 
    description: 'Mainframe user ID'
    required: false
  pass:
    description: 'Mainframe password'
    required: false
  certificate:
    description: 'Client certificate'
    required: false
  runtimeConfiguration:
    description: 'Runtime configuration'
    required: true
    default: ''
  stream:
    description: 'The ISPW Stream name'
    required: true
    default: 'PLAY'
  application:
    description: 'The ISPW Application'
    required: true
    default: 'PLAY'
  subAppl:
    description: 'The ISPW Sub Application'
    required: false
  checkoutLevel:
    description: 'The test level to check components out to'
    required: true
    default: 'DEV1'
  gitUid:
    description: 'GitHub user ID'
    required: true
  gitToken:
    description: 'GitHub token, PAT,  or password when not using GitHub API to calculate the changed files'
    required: true
  containerCreation:
    description: 'The option to indicate how often to create a new ISPW container'
    required: false
  containerDescription:
    description: 'The custom description to be used for the ISPW container'
    required: false
  winTopazPath:
    description: 'Topaz CLI installed path on Window based self-hosted runner'
    required: false
  unixTopazPath:
    description: 'Topaz CLI installed path on Unix based self-hosted runner'
    required: false
  showEnv:
    description: 'Show environment variables for debug purpose'
    required: false
outputs:
  automaticBuildJson:
    description: 'The automatic build parameters JSON'
  changedProgramsJson:
    description: 'The changed programs JSON'
runs:
  using: 'node12'
  main: 'dist/index.js'
